### ISSUE TITLE
Yarn PnP support

### ISSUE THREAD

**Issue by NMinhNguyen** [antfu/local-pkg#2]
I'm trying to use Vitest and I'm running into an issue with Yarn PnP:

> .pnp.cjs:101340 Uncaught Error: local-pkg tried to access vite, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
> 
> Required package: vite (via "vite/package.json")
> Required by: local-pkg@npm:0.4.0 (via /Users/minh/dev/project/.yarn/cache/local-pkg-npm-0.4.0-c31827f33b-46964cea4b.zip/node_modules/local-pkg/)

I believe that this package needs to support [`basedir`](https://github.com/browserify/resolve#resolveid-opts-cb) (similar to `resolve`), and set the [`paths` ](https://nodejs.org/api/modules.html#requireresolverequest-options) option of `require.resolve`:

https://github.com/antfu/local-pkg/blob/fc9d06c5a43485d83f41ec35dfc842e1f6d45aa5/index.mjs#L51-L65

**Comment by TeemuKoivisto** [comment]
Yes this is still an issue. Is there an easy fix for this?

**Comment by sirganya** [comment]
bump

**Comment by JoshuaKGoldberg** [comment]
This also happens with [pnpm](https://pnpm.io): https://github.com/vitest-dev/vitest/issues/3112.

**Comment by francoisauclair911** [comment]
bump

**Comment by wojtekmaj** [comment]
FYI - Vitest no longer uses local-pkg as of version 2.0.0, and therefore, PnP issues are also gone.
