### ISSUE TITLE
No matching export in "browser-external:fs" for import "existsSync"

### ISSUE THREAD

**Issue by softboy99** [antfu/local-pkg#3]
No matching export in "browser-external:fs" for import "existsSync"

**Comment by antfu** [comment]
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)
